In [37]:
import random
import numpy as np
import math
import copy

In [38]:
##### 读.fa
fa_in = open("D:/IntroToDataMining-CS412/final project/benchmark/dataset69/sequences.fa","r")
fa_Seq = []#定义一个列表，用于存储序列
fa_Num = 0
for line in fa_in.readlines():#每次从FASTA文件中读取一行
    line = line.rstrip()#去掉行末的换行符
    fa_Num = fa_Num + 1
    fa_Seq.append(line)
#fa_Seq
##### 读motif 长度
motiflen_in = open("D:/IntroToDataMining-CS412/final project/benchmark/dataset69/motiflength.txt","r")
motif_len = int(motiflen_in.readline())
#motif_len

In [39]:
site_in = open("D:/IntroToDataMining-CS412/final project/benchmark/dataset69/sites.txt","r")
site_Seq = []#定义一个列表，用于存储序列
for line in site_in.readlines():#每次从FASTA文件中读取一行
    line = line.rstrip()#去掉行末的换行符
    site_Seq.append(line)

In [40]:
site_Seq

['474',
 '118',
 '122',
 '301',
 '320',
 '241',
 '395',
 '334',
 '418',
 '436',
 '185',
 '5',
 '209',
 '231',
 '139',
 '400',
 '376',
 '457',
 '78',
 '133']

In [41]:
fa_Seq

['TACGCCACTACATTGGGGGAGGAAACCCTCCTAACGAGACACGGGCACTATCCTCCGCCGAATAGAAGATAACTATACCTGGGGATAATTGCTGGAATAGGTCACCTGTATCCATTTCTATGCTTCTAGGCGGCAGAAGTTTGTGTTTCACGCAAGGTGGGTGCAGGAGGTGTCTAATGTGCTTCTTGCCGCAACAAAACACTACGTTTGATCCTCATTGACAGGCGATCGGCGAGCCGTCAAGAGATCACTGCTGAATTCCTCACACGACGGTGTCCAATGTCATCATCAGACAAAAGTGAGAGTATGCAAATGCGTATCGATTAGCAGCTAAGGCTTAAGTGGCTAGGGGATGCAAATAGATATTTGAAGGTTTACATCCGCATTTGGTGTGGTCAAAAATTGTACGACGGCAATACAGCAGAGACGCATGGTCCTAAATGGAATGGACCGTTGACGTTATACAGCCAGGCGCCTGGACACTCTTCCCGGCGGTTAGC',
 'TTCAAGTATACTCGGTATAAAATGCGCAGTCAGGCTGATGAGCGGCGCAATCCTCTTCTTTGTACCCCTGTACTCCGTGAAGCGCCCAATGATTATTTGAATCCTAGTCTACATTTAACCTGGACAAGTATAGTACTGTCAGTACCCGGATCTGTGCTCTGTGCATTATAGCGATACGAAGACGCATGATAGCACATAGGACTGAGAAAACCCTTTGTGTGCCGCACATCAAGGGCTATAGTGAGAACAATACAGGATCGATTATAGGCCGAAGCCAGTCTACTTTAGAGGAGCCTGGTATTACAATGCTTCGTAAGATTACCTCGCTTGCTAGTGCCTAGTTGTCTGGAGGTGAACGCGTTAGCATAAATGGTGCCTAGACATTTAATCCCAGCATACACAGTTGACATGTTTATTATAGGAAACTTAGGCCTACAACGTGACACCCCATTCCGAGCGACCTATCTTAATAGCGAATCGTGCTCCGACGGTC

In [6]:
fa_Seq
fa_Num
motif_len
site_Seq
for i in range(len(fa_Seq)):
    fa_Seq[i] = fa_Seq[i][int(site_Seq[i]):int(site_Seq[i])+15]

In [7]:
test = []
for i in fa_Seq:
    test.append(i[:motif_len])
test

['CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA',
 'CCTGGACA']

In [8]:
psudo_count_matrix = [[0 for i in range(motif_len)] for j in range(4)] #生成psudo_count_matrix
for i in range(motif_len):
    for j in range(fa_Num-1):
        if test[j][i] == 'A':
            psudo_count_matrix[0][i] += 1
        elif test[j][i] == 'T':
            psudo_count_matrix[1][i] += 1
        elif test[j][i] == 'C':
            psudo_count_matrix[2][i] += 1
        elif test[j][i] == 'G':
            psudo_count_matrix[3][i] += 1
psudo_count_matrix = np.array(psudo_count_matrix) #pro_matrixpsudo_count_matrix   
psudo_count_matrix

array([[ 0,  0,  0,  0,  0, 19,  0, 19],
       [ 0,  0, 19,  0,  0,  0,  0,  0],
       [19, 19,  0,  0,  0,  0, 19,  0],
       [ 0,  0,  0, 19, 19,  0,  0,  0]])

In [42]:
def generate_prob(pro_matrix,k_mer): #k_mer 'CAAATCCC'
    '''
    给定pro_matrix的情况下，出现当前k_mer的概率
    '''
    dic = {'A':0,'T':1,'C':2,'G':3}
    p = 1
    for i in range(len(k_mer)):
        p = p * pro_matrix[dic[k_mer[i]]][i]
    return p

In [43]:
def background_prob(fa_Seq,sites,motif_len):
    dic = {'A':0,'T':1,'C':2,'G':3}
    background_c = np.zeros(4)
    for i in range(len(fa_Seq)):
        for j in range(len(fa_Seq[i])):
            if j not in list(range(sites[i],sites[i]+motif_len)):
                background_c[dic[fa_Seq[i][j]]] +=1
    background_p = background_c/sum(background_c)
    return background_p

In [44]:
def F_given_model(temp_k_mers,background_p,f):
    '''
    计算F(计算F 若更新使F变大，更新；若不能变大，不更新)
    temp_k_mers : 
    [['A', 'C', 'G', 'T', 'T', 'A', 'C', 'T'],
     ['T', 'G', 'G', 'G', 'C', 'C', 'A', 'A'],
     ['T', 'G', 'A', 'C', 'A', 'T', 'G', 'A'],
     ['C', 'C', 'C', 'G', 'T', 'G', 'A', 'C'],
     ['G', 'A', 'T', 'C', 'C', 'A', 'C', 'A'],
     ['G', 'G', 'T', 'T', 'G', 'T', 'T', 'A'],
     ['T', 'G', 'G', 'T', 'G', 'T', 'C', 'A'],
     ['G', 'G', 'T', 'G', 'G', 'G', 'T', 'T'],
     ['A', 'T', 'T', 'C', 'C', 'G', 'C', 'A'],
     ['C', 'C', 'G', 'A', 'A', 'T', 'A', 'T']]
    background_p : [0.2496, 0.2492, 0.2516, 0.2496]
    '''
    dic = {'A':0,'T':1,'C':2,'G':3}
    sigma = ['A','T','C','G']
    
    #motif_count_matrix
    count_matrix = [[0 for i in range(motif_len)] for j in range(4)]
    for i in range(motif_len):
        for j in range(fa_Num):
            if temp_k_mers[j][i] == 'A':
                count_matrix[0][i] += 1
            elif temp_k_mers[j][i] == 'T':
                count_matrix[1][i] += 1
            elif temp_k_mers[j][i] == 'C':
                count_matrix[2][i] += 1
            elif temp_k_mers[j][i] == 'G':
                count_matrix[3][i] += 1
    count_matrix = np.array(count_matrix)
    '''
    [[3, 2, 2, 2, 3, 3, 4, 6],
     [3, 2, 5, 3, 3, 4, 3, 4],
     [3, 4, 2, 4, 4, 2, 4, 2],
     [4, 5, 4, 4, 3, 4, 2, 1]]
    '''
    
    #motif_probability_matrix
    pro_matrix = count_matrix/fa_Num
    '''
    [[0.23076923 0.15384615 0.15384615 0.15384615 0.23076923 0.23076923
      0.30769231 0.46153846]
     [0.23076923 0.15384615 0.38461538 0.23076923 0.23076923 0.30769231
      0.23076923 0.30769231]
     [0.23076923 0.30769231 0.15384615 0.30769231 0.30769231 0.15384615
      0.30769231 0.15384615]
     [0.30769231 0.38461538 0.30769231 0.30769231 0.23076923 0.30769231
      0.15384615 0.07692308]]
    ''' 
    
    flag = False #update
    temp_f = copy.deepcopy(f)
    for i in range(len(temp_k_mers[0])):
        newEntropy = 0
        for j in range(4):
            if pro_matrix[j][i] == 0:
                newEntropy -= 0
            else:
                newEntropy -= pro_matrix[j][i]*math.log(pro_matrix[j][i],2)
        temp_f[i] = newEntropy
        if newEntropy > f[i]:
            flag = True #don't update
    if flag:
        return flag,f 
    else:
        return flag,temp_f

In [45]:
random.randint(0,fa_Num-1)

16

In [46]:
########################################## 无F
######### 设初值 
##### step1 随机选初始site
sites = [random.randint(0, (len(fa_Seq[0])-motif_len)) for i in range(fa_Num)] 
k_mers = []
for i in range(fa_Num):
    k_mers.append(list(fa_Seq[i][sites[i]:sites[i]+motif_len]))
f = [float('inf') for i in range(motif_len)]
A = []
B = []


######### 开始循环
hide_index = 0
not_converge = True
while not_converge:  
    hide_same = True
    while hide_same:
        new_hide_index = random.randint(0,fa_Num-1)#随机隐藏一行
        if new_hide_index != hide_index:
            hide_same = False
            hide_index = new_hide_index
    temp_motif_matrix = k_mers[:hide_index]+k_mers[hide_index+1:] #生成临时motif matrix
    psudo_count_matrix = [[1 for i in range(motif_len)] for j in range(4)] #生成psudo_count_matrix
    
    for i in range(motif_len):
        for j in range(fa_Num-1):
            if temp_motif_matrix[j][i] == 'A':
                psudo_count_matrix[0][i] += 1
            elif temp_motif_matrix[j][i] == 'T':
                psudo_count_matrix[1][i] += 1
            elif temp_motif_matrix[j][i] == 'C':
                psudo_count_matrix[2][i] += 1
            elif temp_motif_matrix[j][i] == 'G':
                psudo_count_matrix[3][i] += 1
    psudo_count_matrix = np.array(psudo_count_matrix) #pro_matrixpsudo_count_matrix     
    pro_matrix = psudo_count_matrix/(fa_Num-1+4) #生成pro_matrix
    prob = [] #按概率选择hiden string的一个k_mer 用来更新对应行的 motif matrix
    hiden_string = fa_Seq[hide_index]
    
    for i in  range(len(fa_Seq[0])-motif_len+1):
        temp_k_mer = hiden_string[i:i+motif_len]
        prob.append(generate_prob(pro_matrix,temp_k_mer))
    # site 暂时更新
    updated_site = np.random.choice(len(fa_Seq[0])-motif_len+1,1,p = prob/sum(prob))[0]  
    temp_sites = copy.deepcopy(sites)
    temp_sites[hide_index] = updated_site # 更新site(temp_site)
    # k_mers 暂时更新
    temp_k_mers = copy.deepcopy(k_mers)
    temp_k_mers[hide_index] = list(fa_Seq[hide_index][sites[hide_index]:sites[hide_index]+motif_len]) # 新的k_mers(temp_k_mers)
    if temp_sites == sites:
        not_converge = False
    sites = copy.deepcopy(temp_sites)
    k_mers = copy.deepcopy(temp_k_mers)  
    A.append(sites)
    B.append(k_mers)
A


[[226,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  48,
  113,
  199,
  403,
  354,
  449,
  459,
  301],
 [226,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  48,
  113,
  199,
  403,
  424,
  449,
  459,
  301],
 [346,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  48,
  113,
  199,
  403,
  424,
  449,
  459,
  301],
 [346,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  306,
  113,
  199,
  403,
  424,
  449,
  459,
  301],
 [346,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  306,
  113,
  199,
  403,
  424,
  449,
  459,
  333],
 [346,
  234,
  477,
  80,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  306,
  366,
  199,
  403,
  424,
  449,
  459,
  333],
 [346,
  234,
  477,
  245,
  116,
  130,
  266,
  468,
  279,
  202,
  55,
  399,
  306,
  366,
  199,
  403,
  424,
  449,
  459,
  333],
 [346,
  234,
  477,
  245,
 

In [34]:
fa_Num

20

In [47]:
B = B[-1]
psudo_count_matrix = [[0 for i in range(motif_len)] for j in range(4)] #生成psudo_count_matrix
for i in range(motif_len):
    for j in range(fa_Num):
        if B[j][i] == 'A':
            psudo_count_matrix[0][i] += 1
        elif B[j][i] == 'T':
            psudo_count_matrix[1][i] += 1
        elif B[j][i] == 'C':
            psudo_count_matrix[2][i] += 1
        elif B[j][i] == 'G':
            psudo_count_matrix[3][i] += 1
psudo_count_matrix = np.array(psudo_count_matrix) #pro_matrixpsudo_count_matrix   
psudo_count_matrix/fa_Num

#341444

array([[0.25, 0.2 , 0.05, 0.25, 0.35, 0.1 , 0.55, 0.2 ],
       [0.35, 0.35, 0.4 , 0.3 , 0.4 , 0.25, 0.05, 0.35],
       [0.35, 0.35, 0.25, 0.2 , 0.05, 0.45, 0.3 , 0.05],
       [0.05, 0.1 , 0.3 , 0.25, 0.2 , 0.2 , 0.1 , 0.4 ]])

In [48]:
########################################## 有F
######### 设初值 
##### step1 随机选初始site
sites = [random.randint(0, (len(fa_Seq[0])-motif_len)) for i in range(fa_Num)] 
k_mers = []
for i in range(fa_Num):
    k_mers.append(list(fa_Seq[i][sites[i]:sites[i]+motif_len]))
f = [float('inf') for i in range(motif_len)]
A = []
B = [[]]


######### 开始循环
iteration_n = 1000
for itera in range(iteration_n):    
    hide_index = random.randint(0,fa_Num-1)#随机隐藏一行
    temp_motif_matrix = k_mers[:hide_index]+k_mers[hide_index+1:] #生成临时motif matrix
    psudo_count_matrix = [[0.01 for i in range(motif_len)] for j in range(4)] #生成psudo_count_matrix
    for i in range(motif_len):
        for j in range(fa_Num-1):
            if temp_motif_matrix[j][i] == 'A':
                psudo_count_matrix[0][i] += 1
            elif temp_motif_matrix[j][i] == 'T':
                psudo_count_matrix[1][i] += 1
            elif temp_motif_matrix[j][i] == 'C':
                psudo_count_matrix[2][i] += 1
            elif temp_motif_matrix[j][i] == 'G':
                psudo_count_matrix[3][i] += 1
    psudo_count_matrix = np.array(psudo_count_matrix) #pro_matrixpsudo_count_matrix     
    pro_matrix = psudo_count_matrix/(fa_Num-1+4) #生成pro_matrix
    prob = [] #按概率选择hiden string的一个k_mer 用来更新对应行的 motif matrix
    hiden_string = fa_Seq[hide_index]
    
    for i in  range(len(fa_Seq[0])-motif_len+1):
        temp_k_mer = hiden_string[i:i+motif_len]
        prob.append(generate_prob(pro_matrix,temp_k_mer))
    # site 暂时更新
    updated_site = np.random.choice(len(fa_Seq[0])-motif_len+1,1,p = prob/sum(prob))[0]  
    temp_sites = copy.deepcopy(sites)
    temp_sites[hide_index] = updated_site # 更新site(temp_site)
    # k_mers 暂时更新
    temp_k_mers = copy.deepcopy(k_mers)
    temp_k_mers[hide_index] = list(fa_Seq[hide_index][sites[hide_index]:sites[hide_index]+motif_len]) # 新的k_mers(temp_k_mers)
    # 计算 background probability
    background_p = background_prob(fa_Seq,temp_sites,motif_len)

    # 计算entropy
    flag, f = F_given_model(temp_k_mers,background_p,f)
    #print(temp_F)
    if not flag:
        sites = copy.deepcopy(temp_sites)
        k_mers = copy.deepcopy(temp_k_mers)
        
    A.append(sites)
    #print(k_mers)
    if itera in [iteration_n-4,iteration_n-3,iteration_n-2,iteration_n-1]:
        print(itera)
        B.append(k_mers)

996
997
998
999


In [23]:
B

[[],
 [['C', 'T', 'G', 'G', 'A', 'C', 'A', 'C'],
  ['G', 'A', 'C', 'A', 'A', 'G', 'T', 'A'],
  ['C', 'A', 'G', 'T', 'T', 'C', 'T', 'G'],
  ['A', 'C', 'A', 'T', 'G', 'C', 'C', 'G'],
  ['C', 'A', 'C', 'A', 'A', 'A', 'A', 'G'],
  ['C', 'A', 'G', 'A', 'G', 'G', 'C', 'G'],
  ['T', 'G', 'G', 'A', 'C', 'A', 'C', 'C'],
  ['A', 'A', 'A', 'C', 'A', 'C', 'T', 'A'],
  ['C', 'A', 'C', 'G', 'G', 'G', 'A', 'T'],
  ['C', 'T', 'G', 'G', 'A', 'C', 'A', 'A'],
  ['A', 'A', 'C', 'C', 'T', 'A', 'A', 'C'],
  ['G', 'A', 'C', 'A', 'C', 'T', 'C', 'A'],
  ['C', 'T', 'G', 'G', 'A', 'C', 'A', 'T'],
  ['C', 'A', 'G', 'T', 'G', 'A', 'G', 'G'],
  ['C', 'A', 'C', 'A', 'C', 'C', 'C', 'T'],
  ['C', 'C', 'T', 'G', 'G', 'A', 'C', 'A'],
  ['A', 'G', 'G', 'A', 'T', 'G', 'T', 'T'],
  ['C', 'T', 'G', 'G', 'A', 'C', 'A', 'G'],
  ['A', 'C', 'A', 'C', 'T', 'C', 'A', 'C'],
  ['G', 'A', 'C', 'A', 'C', 'G', 'T', 'G']],
 [['C', 'T', 'G', 'G', 'A', 'C', 'A', 'C'],
  ['G', 'A', 'C', 'A', 'A', 'G', 'T', 'A'],
  ['C', 'A', 'G', 'T', 'T'

In [297]:
[random.randint(0, (len(fa_Seq[0])-motif_len)) for i in range(fa_Num)] 

[148, 358, 322, 274, 251, 349, 250, 76, 88, 99]

In [ ]:
################################################试一下不加F->converge

In [49]:
B = B[-1]
psudo_count_matrix = [[0 for i in range(motif_len)] for j in range(4)] #生成psudo_count_matrix
for i in range(motif_len):
    for j in range(fa_Num-1):
        if B[j][i] == 'A':
            psudo_count_matrix[0][i] += 1
        elif B[j][i] == 'T':
            psudo_count_matrix[1][i] += 1
        elif B[j][i] == 'C':
            psudo_count_matrix[2][i] += 1
        elif B[j][i] == 'G':
            psudo_count_matrix[3][i] += 1
psudo_count_matrix = np.array(psudo_count_matrix) #pro_matrixpsudo_count_matrix   
psudo_count_matrix

array([[11,  4,  4,  3,  6,  5,  5,  5],
       [ 2,  2,  4,  5,  3,  4,  1,  3],
       [ 0,  7,  7,  8,  5,  2,  7,  3],
       [ 6,  6,  4,  3,  5,  8,  6,  8]])

In [246]:
pro_matrix

array([[0.15461538, 0.00076923, 0.00076923, 0.30846154, 0.00076923,
        0.07769231],
       [0.30846154, 0.30846154, 0.23153846, 0.15461538, 0.23153846,
        0.23153846],
       [0.00076923, 0.38538462, 0.23153846, 0.23153846, 0.38538462,
        0.30846154],
       [0.23153846, 0.00076923, 0.23153846, 0.00076923, 0.07769231,
        0.07769231]])

In [183]:
def F_given_model(temp_k_mers,background_p):
    '''
    计算F(计算F 若更新使F变大，更新；若不能变大，不更新)
    temp_k_mers : 
    [['A', 'C', 'G', 'T', 'T', 'A', 'C', 'T'],
     ['T', 'G', 'G', 'G', 'C', 'C', 'A', 'A'],
     ['T', 'G', 'A', 'C', 'A', 'T', 'G', 'A'],
     ['C', 'C', 'C', 'G', 'T', 'G', 'A', 'C'],
     ['G', 'A', 'T', 'C', 'C', 'A', 'C', 'A'],
     ['G', 'G', 'T', 'T', 'G', 'T', 'T', 'A'],
     ['T', 'G', 'G', 'T', 'G', 'T', 'C', 'A'],
     ['G', 'G', 'T', 'G', 'G', 'G', 'T', 'T'],
     ['A', 'T', 'T', 'C', 'C', 'G', 'C', 'A'],
     ['C', 'C', 'G', 'A', 'A', 'T', 'A', 'T']]
    background_p : [0.2496, 0.2492, 0.2516, 0.2496]
    '''
    dic = {'A':0,'T':1,'C':2,'G':3}
    sigma = ['A','T','C','G']
    
    #motif_count_matrix
    count_matrix = [[0 for i in range(motif_len)] for j in range(4)]
    for i in range(motif_len):
        for j in range(fa_Num):
            if temp_k_mers[j][i] == 'A':
                count_matrix[0][i] += 1
            elif temp_k_mers[j][i] == 'T':
                count_matrix[1][i] += 1
            elif temp_k_mers[j][i] == 'C':
                count_matrix[2][i] += 1
            elif temp_k_mers[j][i] == 'G':
                count_matrix[3][i] += 1
    count_matrix = np.array(count_matrix)
    '''
    [[3, 2, 2, 2, 3, 3, 4, 6],
     [3, 2, 5, 3, 3, 4, 3, 4],
     [3, 4, 2, 4, 4, 2, 4, 2],
     [4, 5, 4, 4, 3, 4, 2, 1]]
    '''
    
    #motif_probability_matrix
    pro_matrix = count_matrix/fa_Num
    '''
    [[0.23076923 0.15384615 0.15384615 0.15384615 0.23076923 0.23076923
      0.30769231 0.46153846]
     [0.23076923 0.15384615 0.38461538 0.23076923 0.23076923 0.30769231
      0.23076923 0.30769231]
     [0.23076923 0.30769231 0.15384615 0.30769231 0.30769231 0.15384615
      0.30769231 0.15384615]
     [0.30769231 0.38461538 0.30769231 0.30769231 0.23076923 0.30769231
      0.15384615 0.07692308]]
    '''
    #print(count_matrix)
    F = 0
    for i in range(len(temp_k_mers[0])):
        for j in range(4):
            if count_matrix[j][i] == 0:
                F += 0
            else:
                F += count_matrix[j][i]*math.log2(pro_matrix[j][i]/background_p[j])
    return F